Isen.DotNet.Web/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Isen.DotNet.Library.Repositories.InMemory;
using Isen.DotNet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Web.Controllers
{
    public class CityController : BaseController<City>
    {
        public CityController(
            ILogger<CityController> logger,
            ICityRepository repository) 
            : base(logger, repository)
        {
        }
    }
}

Isen.DotNet.Web/Views/City/Detail.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@{
    ViewData["Title"] = "City (détail)";
}
@model City

<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/city/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" asp-action="Detail">
            <input type="hidden" value="@Model?.Id" asp-for="Id" />
            <div>
                <label for="Name" class="control-label">Nom de la ville :</label>
                
            </div>
            <br />
            <input type="submit" class="btn btn-primary" value="Valider" />
            <a class="btn btn-default" 
                asp-controller="City" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Isen.DotNet.Web/Views/City/Index.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Villes";
}
@model IEnumerable<City>

<div class="row">
    <div class="col-md-12">
        <h1>Villes <small>/city/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="City" asp-action="Detail">Ajouter une ville...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Population</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var city in Model)
            {
            <tr>
                <td>@city.Id</td>
                <td></td>
                <td>@city.PersonCount</td>
                <td>
                    <a class="btn btn-default" asp-controller="City" asp-action="Detail" asp-route-id="@city.Id">Editer</a>
                    &nbsp;
                    <a class="btn btn-danger" asp-controller="City" asp-action="Delete" asp-route-id="@city.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>