Isen.DotNet.Web/Controllers/PointOfInterestController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Isen.DotNet.Library.Repositories.InMemory;
using Isen.DotNet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;
using Isen.DotNet.Library.Models;

namespace Isen.DotNet.Web.Controllers
{
    public class PointOfInterestController : BaseController<PointOfInterest>
    {
        public PointOfInterestController(
            ILogger<PointOfInterestController> logger,
            IPointOfInterestRepository repository) 
            : base(logger, repository)
        {
        }
    }
}

Isen.DotNet.Web/Views/PointOfInterest/Detail.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@using Isen.DotNet.Library.Repositories.Interfaces;

@inject ICategoryRepository _categoryRepository;
@inject IAddressRepository _addressRepository;
@model Isen.DotNet.Library.Models.Implementation.PointOfInterest

@{
	ViewData["Title"] = "Detail";
}

<h2>Detail</h2>

<h4>PointOfInterest</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Detail">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>
			<div class="form-group">
				@Html.DropDownListFor(
						 poi => poi.CategoryId,
						 new SelectList(
							 _categoryRepository.GetAll(),
							 "Id",
							 "Name"),
						 "<Sélectionnez une catégorie>",
						 new { @class = "form-control" })
			</div>
			<div class="form-group">
				@Html.DropDownListFor(
				  poi => poi.AddressId,
				  new SelectList(
					  _addressRepository.GetAll(),
					  "Id",
					  "Text"),
				  "<Sélectionnez une addresse>",
				  new { @class = "form-control" })
			</div>
			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Isen.DotNet.Web/Views/PointOfInterest/Index.cshtml
@model IEnumerable<Isen.DotNet.Library.Models.Implementation.PointOfInterest>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<div class="row">
	<a class="btn btn-default"
	   asp-controller="PointOfInterest" asp-action="Detail">Ajouter un point d'intérêt...</a>
</div>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address.Text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>